### ISSUE TITLE
Código Copiado.

### ISSUE THREAD

**Issue by TiaGoiNsaNy** [RafaGamerOFC/TutorialBOT#1]
## :-1: Código Copiado é muito Feio!

:snake: Entrando no seu repositório de cara já percebo que o código não foi desenvolvido por você, sei muito bem que você tentou disfarçar mudando a posição de eventos do projeto. Mais de quem é esse Código? Eu te respondo meu amigo, você copiou o código fonte provavelmente do [@Hyouka](https://www.youtube.com/channel/UC588Isn42hii9Ri0l7G2acA), mais não irei falar sobre isso no momento, vou abordar um assunto que esse código fonte apresenta.

:bug: Em relação a estruturação do projeto, ele é pouco otimizado para as aplicações do Discord de hoje e dia, pois tem muitas brechas não no código principal e sim nos comandos em si. Já começando com a ordem de listagem de eventos do projeto, que normalmente deveriam ser primeiramente o evento **Ready** e logo em seguida o evento **Message**, mais pelo visto você inverteu os dois, não muda muito em relação ao resultado final, mais ajuda em questão de organização, deixando o projeto com uma estrutura **Semântica**.

:computer_mouse: Em relação as comandos do projeto, que por sinal só possuem um, mais em algum motivo você listou no comando de ajuda que possui vários outros comandos, já entrando no modulo de exportação de cada comando, foi definido uma propriedade chamada `run`, que não muda muito também mais pode afetar no desenvolvimento de comandos futuros, recomendo você remover essa propriedade e deixando de modo padrão o `module.exports`, e simplificando seu modulo.

### :file_folder: Exemplo de Exportação de Módulo:

```javascript
module.exports = <Async>() => {
 // Código de seu comando
};
```

:computer: Como no momento do seu **Command Handler** é pouco otimizado para seu ambiente de desenvolvimento, seria necessário adicionar mais uma outra condição no seu evento de **Message**, que acabaria com aquelas mensagens de **Erro** onde não foi encontrado um comando, que ocorre quando um usuário sita o comando inexistente, por exemplo `<prefix>tiagoinsany` e logo após isso o projeto tenta encontrar esse comando inexistente na pasta de comandos, e não obtêm sucesso e gera um erro no console.

### :gear: Condição para Solucionar o Problema:

```javascript
const commandFile = require(`./Comandos/${command}.js`); // Faz a busca do comando solicitado

if (!commandFile) return; // Não retorna nada se não existir o comando.
```

## :thinking: Considerações Finais:

:sneezing_face: Eu não iria continuar com esse projeto exposto para outros usuários do **Github**, pois isso poderia acabar iniciando o envio desse sistema horrível para a comunidade de desenvolvedores iniciantes. Uma frase que aprendi no longo da minha história de programador é: *"Se o código não é seu, o Bot não é seu."* e espero que você também leve essa frase para sua vida e tente desenvolver outros projetos por conta própria. Assim você vai aprender mais, como eu aprendi me desgrudando desses padrões de projeto.

:lock: Sobre a descrição do projeto, está muito errado ao sitar a frase: *"Aprenda a criar um bot em JavaScript"*, afinal não existe nenhuma explicação sobre o **JavaScript** e nem de como criar uma **Aplicação**. Mude isso e seja Feliz! :heart: 

## :link: Links que eu adoraria que você entrasse:

- :bird: **Twitter:** [@TiaGoiNsaNy](https://twitter.com/TiaGoiNsaNy) 
- :speech_balloon: **Discord:** `TiaGoiNsaNy#9903`

**Comment by vitin-ON** [comment]
:0 só verdades

**Comment by zEneeergy** [comment]
@TiaGoiNsaNy Você é o motivo de eu odiar Markdown
